name: Create, Link, and Add Issue to Project from PR

on:
  pull_request:
    types: [opened]

jobs:
  create_link_and_add:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Create Issue and Add to Project
        id: create_issue 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          ISSUE_BODY: |
            Pull Request #${{ github.event.pull_request.number }} foi aberto.

            *Link para o PR:* ${{ github.event.pull_request.html_url }}

            ---

            ### Checklist de Revisão
            - [ ] O código segue os padrões do projeto?
            - [ ] A documentação foi atualizada?
            - [ ] Os testes unitários foram criados/atualizados e estão passando?
            - [ ] A funcionalidade foi testada manualmente?
        run: |
          # Cria a issue, já adicionando ao projeto com a flag -p
          # A saída padrão deste comando é a URL da nova issue
          ISSUE_URL=$(gh issue create --title "Revisão do PR: ${{ env.PR_TITLE }}" \
                                     --body "${{ env.ISSUE_BODY }}" \
                                     --label "revisão-pr" \
                                     --project "DOD")
          
          # Extrai o número da issue a partir da URL e o define como saída
          ISSUE_NUMBER=$(basename "$ISSUE_URL")
          echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT

      - name: Link PR to Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_BODY: ${{ github.event.pull_request.body }}
          ISSUE_NUMBER: ${{ steps.create_issue.outputs.issue_number }}
        run: |
          gh pr edit ${{ env.PR_NUMBER }} --body "${{ env.PR_BODY }}

          Closes #${{ env.ISSUE_NUMBER }}"