name: Create Issue from Pull Request

# Aciona o workflow sempre que um PR for aberto para a branch 'main'
on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  create_centralized_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write        # Permissão para criar issues
      pull-requests: read  # Permissão para ler dados do PR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Centralized Issue
        env:
          # Token de acesso pessoal. É necessário para criar uma issue em OUTRO repositório.
          GH_TOKEN: ${{ secrets.GH_AUTOMATION_PAT }}
          # Nome do seu repositório central (usuário/nome-do-repo)
          CENTRAL_REPO: "gabiminas/repo-central"
          # Título para a nova issue
          ISSUE_TITLE: "PR Aberto: ${{ github.event.pull_request.title }}"
          # Corpo para a nova issue
          ISSUE_BODY: |
            ### Novo Pull Request Aberto
            - *Repositório:* ${{ github.repository }}
            - *PR Original:* [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})
            - *Autor:* @${{ github.actor }}
            
            ---
            
            #### Checklist de Revisão
            - [ ] Revisão de código concluída
            - [ ] Testes automatizados passaram
            - [ ] Documentação atualizada

        run: |
          echo "Criando issue no repositório ${CENTRAL_REPO}..."

          # Usa a CLI do GitHub para criar a issue diretamente no repositório central
          gh issue create --title "$ISSUE_TITLE" --body "$ISSUE_BODY" --repo $CENTRAL_REPO

          echo "Issue criada com sucesso no repositório ${CENTRAL_REPO}!"