name: Create the Definition of Done - DOD issue

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  setup-issue:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: read

    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Issue From Template and Assign
        id: create_issue
        uses: JasonEtco/create-an-issue@v2
        with:
           token: ${{ steps.get_workflow_token.outputs.token }}
           filename: .github/ISSUE_TEMPLATE/todo.md
           assignees: ${{ github.event.pull_request.user.login }}
           title: "DOD para o PR #${{ github.event.pull_request.number }}"

      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/users/gabiminas/projects/1/views/1
          github-token: ${{ steps.get_workflow_token.outputs.token }}
          project-target-id: ${{ steps.create_issue.outputs.node_id }}