name: Create the Definition of Done - DOD issue

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  setup-issue:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Issue From Template
        id: create_issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.get_workflow_token.outputs.token }}
          script: |
            const fs = require('fs');
            const issueTemplate = fs.readFileSync('.github/ISSUE_TEMPLATE/todo.md', 'utf8');
            const prNumber = context.payload.pull_request.number;
            const prAuthor = context.payload.pull_request.user.login;
            const newTitle = `DOD para o PR #${prNumber}`;
            const newBody = issueTemplate;
            const assignees = [prAuthor];

            const { data: issue } = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: newTitle,
              body: newBody,
              assignees: assignees
            });

            console.log(`Issue criada: ${issue.html_url}`);
            core.setOutput('issue_node_id', issue.node_id);

      - name: Add to Project
        uses: actions/add-to-project@v0.6.1
        with:
          project-url: https://github.com/users/gabiminas/projects/1
          github-token: ${{ steps.get_workflow_token.outputs.token }}
          issue-node-id: ${{ steps.create_issue.outputs.issue_node_id }}
